/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package plantillas;

/**
 *
 * @author Alici
 */
public class PanelIngredienteProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngredienteProducto
     */
    public PanelIngredienteProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreIngrediente = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblUnidadMedida = new javax.swing.JLabel();
        lblCantidadTitulo = new javax.swing.JLabel();
        btnMas = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 228, 242));
        setPreferredSize(new java.awt.Dimension(280, 109));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreIngrediente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombreIngrediente.setText("nombre...");
        add(lblNombreIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        lblCantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCantidad.setText("cantidad...");
        add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 60, -1));

        lblUnidadMedida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUnidadMedida.setText("unidad...");
        add(lblUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        lblCantidadTitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCantidadTitulo.setText("Cantidad:");
        add(lblCantidadTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 60, -1));

        btnMas.setBackground(new java.awt.Color(172, 204, 255));
        btnMas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnMas.setText("+");
        btnMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 60, -1));

        btnMenos.setBackground(new java.awt.Color(172, 204, 255));
        btnMenos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnMenos.setText("—");
        btnMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });
        add(btnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidadTitulo;
    private javax.swing.JLabel lblNombreIngrediente;
    private javax.swing.JLabel lblUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
