/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moduloProductos;

import DTOs.ProductoDTO;
import java.awt.GridLayout;
import java.util.List;
import plantillas.PanelProducto;

/**
 *
 * @author Alici
 */
public class PanelVistaGridProductos extends javax.swing.JPanel implements VistaProductos {

    /**
     * Creates new form PanelProductosTomaComanda
     */
    public PanelVistaGridProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanelProductos = new javax.swing.JScrollPane();
        panelContenedorProductos = new javax.swing.JPanel();

        scrollPanelProductos.setBackground(new java.awt.Color(255, 254, 245));
        scrollPanelProductos.setBorder(null);
        scrollPanelProductos.setHorizontalScrollBar(null);

        panelContenedorProductos.setBackground(new java.awt.Color(255, 254, 245));
        panelContenedorProductos.setMaximumSize(new java.awt.Dimension(790, 578));
        panelContenedorProductos.setMinimumSize(new java.awt.Dimension(790, 578));
        panelContenedorProductos.setLayout(new java.awt.GridLayout(0, 5));
        scrollPanelProductos.setViewportView(panelContenedorProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(scrollPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(scrollPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelContenedorProductos;
    private javax.swing.JScrollPane scrollPanelProductos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarProductos(List<ProductoDTO> productos) {
        for (ProductoDTO producto : productos) {
            panelContenedorProductos.add(new PanelProducto(producto));
        }

    }
}
